/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/adicionar` | `/adicionar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/configs` | `/configs`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/detalhes_produto` | `/detalhes_produto`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/editar_produto` | `/editar_produto`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/estoque` | `/estoque`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/relatorios` | `/relatorios`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/adicionar` | `/adicionar`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/configs` | `/configs`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/detalhes_produto` | `/detalhes_produto`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/editar_produto` | `/editar_produto`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/estoque` | `/estoque`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/relatorios` | `/relatorios`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/adicionar${`?${string}` | `#${string}` | ''}` | `/adicionar${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/configs${`?${string}` | `#${string}` | ''}` | `/configs${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/detalhes_produto${`?${string}` | `#${string}` | ''}` | `/detalhes_produto${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/editar_produto${`?${string}` | `#${string}` | ''}` | `/editar_produto${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/estoque${`?${string}` | `#${string}` | ''}` | `/estoque${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/relatorios${`?${string}` | `#${string}` | ''}` | `/relatorios${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/adicionar` | `/adicionar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/configs` | `/configs`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/detalhes_produto` | `/detalhes_produto`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/editar_produto` | `/editar_produto`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/estoque` | `/estoque`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/relatorios` | `/relatorios`; params?: Router.UnknownInputParams; };
    }
  }
}
